import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
  servicesSidebar: [{ type: 'autogenerated', dirName: 'services' }],
  troubleshootSidebar: [{ type: 'autogenerated', dirName: 'troubleshoot' }],
  corporateSidebar: [{ type: 'autogenerated', dirName: 'corporate' }],
  changelogSidebar: [{ type: 'autogenerated', dirName: 'changelog' }],

  // Manually defined API sidebar with autogenerated subcategories
  apiSidebar: [
    'api/getting-started', 
    'api/system-models', 
    'api/faqs',
    {
      type: 'category',
      label: 'Registration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/registration',
        },
      ],
    },

    {
      type: 'category',
      label: 'User',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/user',
        },
      ],
    },

    {
      type: 'category',
      label: 'Avatar',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/avatar',
        },
      ],
    },

    {
      type: 'category',
      label: 'Auction',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/auction',
        },
      ],
    },

    {
      type: 'category',
      label: 'Bid',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/bid',
        },
      ],
    },

    {
      type: 'category',
      label: 'Presale',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/presale',
        },
      ],
    },

    {
      type: 'category',
      label: 'Presale Orders',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/presale-orders',
        },
      ],
    },

    {
      type: 'category',
      label: 'Presale Payment',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/presale-payment',
        },
      ],
    },

    {
      type: 'category',
      label: 'Deposit',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/deposit',
        },
      ],
    },

    {
      type: 'category',
      label: 'Withdraw',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/withdraw',
        },
      ],
    },

    // {
    //   type: 'category',
    //   label: 'Referral',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'api/referral',
    //     },
    //   ],
    // },

    {
      type: 'category',
      label: 'Profile',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/profile',
        },
      ],
    },

    {
      type: 'category',
      label: 'User Tier',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/user-tier',
        },
      ],
    },

    {
      type: 'category',
      label: 'Notification',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/notification',
        },
      ],
    },

    {
      type: 'category',
      label: 'Statistics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/statistics',
        },
      ],
    },

    {
      type: 'category',
      label: 'Social Login (OAuth2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/oauth2',
        },
      ],
    },

  ],
};

export default sidebars;