/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "NYYU Resource Center",
  "tagline": "The NYYU Resource Center is your ultimate destination for comprehensive helpdesk, in-depth tutorials, FAQs, development APIs, and the latest updates on the NYYU platform.",
  "favicon": "img/favicon.ico",
  "url": "https://docs.nyyu.io",
  "baseUrl": "/",
  "organizationName": "NYYU",
  "projectName": "NYYU Resource Center",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {
      "en": {
        "label": "English",
        "direction": "ltr",
        "htmlLang": "en-US",
        "calendar": "gregory",
        "path": "en"
      }
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "algolia": {
      "appId": "IZZT1AVCRI",
      "apiKey": "057c1a9353cae106544caf567cf84d25",
      "indexName": "orbvpn",
      "contextualSearch": true,
      "externalUrlRegex": "external\\.com|domain\\.com",
      "replaceSearchResultPathname": {
        "from": "/docs/",
        "to": "/"
      },
      "searchParameters": {},
      "searchPagePath": "search",
      "insights": false
    },
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "logo": {
        "alt": "NYYU Logo",
        "src": "img/logo.svg",
        "srcDark": "img/logo_dark.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Tutorial"
        },
        {
          "type": "docSidebar",
          "sidebarId": "troubleshootSidebar",
          "position": "left",
          "label": "FAQ"
        },
        {
          "type": "docSidebar",
          "sidebarId": "apiSidebar",
          "position": "left",
          "label": "API"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://nyyu.io",
          "label": "Login",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false,
      "title": ""
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Products",
          "items": [
            {
              "label": "Trade",
              "to": "/docs/tutorial-basics/nyyu-trade"
            },
            {
              "label": "Swap",
              "to": "/docs/tutorial-basics/nyyu-swap"
            },
            {
              "label": "Marketplace",
              "to": "/docs/tutorial-basics/Marketplace/intro"
            },
            {
              "label": "Loan",
              "to": "/docs/tutorial-basics/loan"
            },
            {
              "label": "Save",
              "to": "/docs/tutorial-basics/save"
            },
            {
              "label": "Invites",
              "to": "/docs/tutorial-basics/invites"
            }
          ]
        },
        {
          "title": "Services",
          "items": [
            {
              "label": "Token Listing",
              "to": "/"
            },
            {
              "label": "Startup Listing",
              "href": "/"
            },
            {
              "label": "Property Listing",
              "to": "/"
            },
            {
              "label": "Commodity Listing",
              "href": "/"
            },
            {
              "label": "Fees",
              "to": "/"
            },
            {
              "label": "Bug Boutny",
              "to": "/"
            },
            {
              "label": "Delistings",
              "to": "/"
            },
            {
              "label": "PoR (Proof of Reserves)",
              "to": "/"
            }
          ]
        },
        {
          "title": "Developers",
          "items": [
            {
              "label": "NYYU API",
              "to": "/"
            },
            {
              "label": "NYYU Node",
              "href": "/"
            },
            {
              "label": "NYYU Pay",
              "to": "/"
            }
          ]
        },
        {
          "title": "Corporate",
          "items": [
            {
              "label": "About Us",
              "to": "/"
            },
            {
              "label": "Media Kit",
              "href": "/"
            },
            {
              "label": "Whistleblower Contact",
              "to": "/"
            },
            {
              "label": "Security",
              "to": "/"
            },
            {
              "label": "Changelogs",
              "href": "/"
            },
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "Contact Us",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "X",
              "href": "https://twitter.com/nyyuio"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/nyyuio/"
            },
            {
              "label": "Instagram",
              "href": "https://instagram.com/nyuuio"
            },
            {
              "label": "Youtube",
              "href": "https://youtube.com/nyyuio"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Terms of Use",
              "to": "/"
            },
            {
              "label": "Privacy Policy",
              "href": "/"
            },
            {
              "label": "Risk Disclosure Statement",
              "to": "/"
            },
            {
              "label": "AML & CFT",
              "href": "/"
            },
            {
              "label": "Special Treatment",
              "to": "/"
            },
            {
              "label": "Law Enforcmement Requests",
              "href": "/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 NYYU UAB"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
